---
- name: Set distro-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
    - default.yml

- name: Install runit
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ runit_packages }}"

- name: Enable runsvdir service
  ansible.builtin.service:
    name: "{{ runit_service }}"
    state: started
