---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: debian-stretch-9
    box: bento/debian-9
    memory: 512
  - name: debian-jessie-8
    box: bento/debian-8
    memory: 512
  - name: ubuntu-trusty-14.04
    box: ubuntu/trusty64
    memory: 512
  - name: ubuntu-xenial-16.04
    box: ubuntu/xenial64
    memory: 512
  - name: ubuntu-bionic-18.04
    box: ubuntu/bionic64
    memory: 512
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
