---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint .
  ansible-lint --exclude molecule
platforms:
  - name: debian-buster-10
    box: bento/debian-10
    memory: 320
  - name: debian-stretch-9
    box: bento/debian-9
    memory: 320
  - name: ubuntu-bionic-18.04
    box: ubuntu/bionic64
    memory: 320
  - name: ubuntu-focal-20.04
    box: ubuntu/focal64
    memory: 320
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
